"""Add DocumentChunk model

Revision ID: 78c9e0a9882e
Revises: f9f38a371d4c
Create Date: 2025-11-19 15:04:57.940447

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '78c9e0a9882e'
down_revision: str | Sequence[str] | None = 'f9f38a371d4c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
